name: Node CI

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                platform:
                    - ubuntu-latest
                node-version:
                    - 16.x
                    - 14.x
        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install, lint, and test
              run: |
                  yarn install --pure-lockfile
                  yarn build
                  yarn test
              env:
                  CI: true
